mysite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from .views import (set_cookie_view, get_cookie_view, set_session_view, get_session_view, logout_view, AboutMeView,
                    RegisterView, FooBarView, ProfileUpdateView, UsersListView, UserDetailsView, HelloView)

app_name = "myauth"

urlpatterns = [
    # path("login/", login_view, name="login"),
    path("hello/", HelloView.as_view(), name="helo"),
    path("login/", LoginView.as_view(template_name="myauth/login.html", redirect_authenticated_user=True),
         name="login"),
    path("logout/", logout_view, name="logout"),
    path("about-me/", AboutMeView.as_view(), name="about-me"),
    path("profile-update/<int:pk>/", ProfileUpdateView.as_view(), name="profile-update"),
    path("users-list/", UsersListView.as_view(), name="users-list"),
    path("user_details/<int:pk>/", UserDetailsView.as_view(), name="user-details"),
    path("register/", RegisterView.as_view(), name="register"),
    # path("logout/", MyLogoutView.as_view(), name="logout"),
    path("cookie/get/", get_cookie_view, name="cookie-get"),
    path("cookie/set/", set_cookie_view, name="cookie-set"),
    path("session/set/", set_session_view, name="session-set"),
    path("session/get/", get_session_view, name="session-get"),
    path("foo-bar/", FooBarView.as_view(), name="foo-bar"),
]

mysite/myauth/models.py
from django.contrib.auth.models import User
from django.db import models


def avatar_images_directory_path(instance: "Profile", filename: str) -> str:
    return "users/user_{pk}/avatars/{filename}".format(
        pk=instance.pk, filename=filename
    )


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    agreement_accepted = models.BooleanField(default=False)
    avatar_image = models.ImageField(null=True, blank=True, upload_to=avatar_images_directory_path)

mysite/myauth/forms.py
from django.forms import ModelForm
from .models import Profile


class ProfileUpdateForm(ModelForm):
    class Meta:
        model = Profile
        fields = "__all__"

mysite/myauth/views.py
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LogoutView
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import TemplateView, CreateView, UpdateView, ListView, DetailView

from django.utils.translation import gettext_lazy as _, ngettext
from .forms import ProfileUpdateForm
from .models import Profile
from random import random
from django.views.decorators.cache import cache_page


class HelloView(View):
    welcome_message = _("welcome hello world")

    def get(self, request: HttpRequest) -> HttpResponse:
        items_str = request.GET.get("items") or 0
        items = int(items_str)
        products_line = ngettext(
            "one product",
            "{count} products",
            items
        )
        products_line = products_line.format(count=items)
        return HttpResponse(
            f"<h1>{self.welcome_message}</h1>"
            f"\n<h2>{products_line}</h2>"
        )


class AboutMeView(TemplateView):
    template_name = "myauth/about-me.html"


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = "myauth/register.html"
    success_url = reverse_lazy("myauth:about-me")

    def form_valid(self, form):
        response = super().form_valid(form)
        Profile.objects.create(user=self.object)
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")

        user = authenticate(self.request, username=username, password=password)
        login(request=self.request, user=user)

        return response


def login_view(request: HttpRequest) -> HttpResponse:
    if request.method == "GET":
        if request.user.is_authenticated:
            return redirect('/admin/')

        return render(request, 'myauth/login.html')

    username = request.POST["username"]
    password = request.POST["password"]

    user = authenticate(request, username=username, password=password)
    if user:
        login(request, user)
        return redirect('/admin/')
    return render(request, 'myauth/login.html', {'error': 'Invalid login credentials'})


def logout_view(request: HttpRequest):
    logout(request)
    return redirect(reverse("myauth:login"))


# class MyLogoutView(LogoutView):
#     next_page = reverse_lazy("myauth:login")
# Deprecated since version 4.1:
# Support for logging out on GET requests is deprecated and will be removed in Django 5.0.

@user_passes_test(lambda u: u.is_superuser)
def set_cookie_view(request: HttpRequest) -> HttpResponse:
    response = HttpResponse("Cookie set")
    response.set_cookie("fizz", "buzz", max_age=3600)
    return response


@cache_page(60 * 2)
def get_cookie_view(request: HttpRequest) -> HttpResponse:
    value = request.COOKIES.get("fizz", "default value")
    return HttpResponse(f"Cookie value: {value!r} + {random()}")


@permission_required("myauth.view_profile", raise_exception=True)
def set_session_view(request: HttpRequest) -> HttpResponse:
    request.session["foobar"] = "spameggs"
    return HttpResponse("Session set!")


@login_required
def get_session_view(request: HttpRequest) -> HttpResponse:
    value = request.session.get("foobar", "default")
    return HttpResponse(f"Session value: {value!r}")


class FooBarView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        return JsonResponse({"foo": "bar", "spam": "eggs"})


class ProfileUpdateView(UserPassesTestMixin, UpdateView):

    def test_func(self):
        if self.request.user.id == self.get_object().user.profile.id or self.request.user.is_staff:
            return True

    model = Profile
    template_name = "myauth/profile-update.html"
    form_class = ProfileUpdateForm

    def get_success_url(self):
        return reverse("myauth:users-list")


class UsersListView(ListView):
    template_name = "myauth/users-list.html"
    context_object_name = "users_list"
    queryset = User.objects.all()


class UserDetailsView(DetailView):
    template_name = 'myauth/user-details.html'
    queryset = User.objects.select_related("profile")
    context_object_name = "user"

mysite/myauth/templates/myauth/about-me.html
{% extends 'myauth/base.html' %}
{% load cache %}

{% block title %}
About me
{% endblock %}

{% block body %}
<h1>User info</h1>
<div>
    Products available: {% now "u" %}
</div>
{% if user.is_authenticated%}
{% cache 300 userinfo user.username %}
<h2>Details</h2>
<p>Username: {{ user.username }}</p>
<p>First name: {{ user.first_name }}</p>
<p>Last name: {{ user.last_name }}</p>
<p>Email: {{ user.email }}</p>
<p>Bio: {{ user.profile.bio }}</p>
{% if user.profile.avatar_image %}
<img src="{{ user.profile.avatar_image.url }}" alt="user.profile.avatar_image.name "><br>
{% else %}
<p>No avatar yet</p>
{% endif%}
<a href="{% url 'myauth:profile-update' pk=user.pk %}">Update profile</a><br>
<a href="{% url 'myauth:users-list' %}">Users list</a>
{% endcache %}
{% else %}
<h2>User is anonymous</h2>
{% endif %}
{% endblock %}

mysite/myauth/templates/myauth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        Base Title
        {% endblock %}
    </title>
    <style>
        a {
              color: black;
              text-decoration: none;
          }
          a:hover{
              color: rgb(14, 14, 136);
              text-decoration: underline;
          }
    </style>
</head>
<body>
{% block body %}
Base Body
{% endblock %}
</body>
</html>

mysite/myauth/templates/myauth/login.html
{% extends 'myauth/base.html' %}

{% block title %}
Login
{% endblock %}

{% block body %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
</form>
{% endblock %}

mysite/myauth/templates/myauth/profile-update.html
{% extends 'myauth/base.html' %}

{% block title %}
Profile Update
{% endblock %}

{% block body %}
<h1>Profile Update</h1>
<div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
    </form>
</div>
{% endblock %}

mysite/myauth/templates/myauth/register.html
{% extends 'myauth/base.html' %}

{% block title %}
Register
{% endblock %}

{% block body %}
<h1>Register</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Register">
</form>
{% endblock %}

mysite/myauth/templates/myauth/user-details.html
{% extends 'myauth/base.html' %}

{% block title %}
User #{{ user.pk }}
{% endblock %}

{% block body %}
<div>
    {% if user.is_authenticated %}
    <h2>Username: <strong>{{ user.username }}</strong></h2><br>
    <div>Bio: {{ user.profile.bio }}</div>
    <div>Lust name: {{ user.last_name }}</div>
    <div>First name: {{ user.first_name }}</div>
    <div>Email: {{ user.email }}</div>

    <div>
        {% if request.user.is_staff or user.pk == request.user.pk %}
        <br><a href="{% url 'myauth:profile-update' user.pk %}">
            Update avatar photo
        </a>
        {% endif %}

    </div>
    {% if user.profile.avatar_image%}
    <br><img src="{{ user.profile.avatar_image.url }}" alt="{{ user.profile.avatar_image.name }}">
    {% endif %}


    <div>
        <br><a href="{% url 'myauth:users-list' %}">Back to users list</a>
    </div>
    {% endif %}
</div>
{% endblock %}

mysite/myauth/templates/myauth/users-list.html
{% extends 'myauth/base.html' %}

{% block title %}
Users list
{% endblock %}


{% block body %}

<div>
    <h3>Users list</h3>

    {% if user.is_authenticated %}

    {% if users_list %}

    {% for user in users_list %}
    <div>
        <p>
            <a href="{% url 'myauth:user-details' pk=user.pk %}">
                {{ user.first_name }} {{ user.last_name }}<br></a>
            {% if user.profile.avatar_image %}
            <img src="{{ user.profile.avatar_image.url }}" alt="{{ user.profile.avatar_image.name }}">
            <br>
            {% else %}
        <h3>No avatar yet</h3>
        {% endif %}
        </p>

    </div>
    {% endfor %}

    {% endif %}
    {% endif %}
</div>
{% endblock %}